services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - ./ssh:/root/.ssh:ro
      - ./data:/app
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@<cluster-url>/<dbname>?retryWrites=true&w=majority
    depends_on:
      - mongo-init
    entrypoint: ["/bin/sh", "/entrypoint.sh"]
    command: tail -f /dev/null

  mongo-init:
    image: alpine
    container_name: mongo_init
    entrypoint: /bin/sh -c "echo 'MongoDB Atlas URI setup complete.'"

